

###
GET http://localhost:3901/api/persons/

###
Delete http://localhost:3901/api/persons/2

###
POST http://localhost:3901/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "number": "random number"
}

###
POST http://localhost:3901/api/persons
Content-Type: application/json

{
    "name": "Miau",
    "time": "Wed, 21 Oct 20134233333327:50 GMT",
    "number": "random number 222"
}