

###
GET http://localhost:3901/api/blogs/

###
GET http://localhost:3901/api/blogs/663d21b9c637b809c55f912d

###
POST http://localhost:3901/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "random title",
  "author": "some author",
  "url": "some random url",
  "likes": 15
}

###
POST http://localhost:3901/api/blogs
Content-Type: application/json

{
  "title": "random title",
  "url": "some random url",
  "likes": 15
}

###
Delete http://localhost:3901/api/blogs/663d30af7331938f0dc9fc2b

###
PUT http://localhost:3901/api/blogs/663d32ef29ffd19178d3577b
Content-Type: application/json

{
    "author": "AAAAAAAAAAA"
  }

